---
- name: Icinga 2 Install
  hosts: all
  become: yes
  tasks:
    - name: CentOS - Add Icinga 2 repository
      yum_repository:
         name: ICINGA-release
         description: Icinga packages for EL
         baseurl: "http://packages.icinga.com/epel/$releasever/release/"
         gpgkey: "https://packages.icinga.com/icinga.key"
         gpgcheck: yes

    - name: CentOS - Ensure EPEL is enabled
      yum:
        name: epel-release
        state: present

    - name: CentOS - Ensure icinga2 is installed
      yum:
        name: icinga2
        state: latest
    - name: Install Icinga Dependencies
      yum:
        name: perl
        state: latest
    - name: Install Nagios Plugins
      yum:
        name: nagios-plugins-all
        state: latest

    - name: CentOS - Enable Icinga 2 Agent
      service:
        name: Icinga2
        enable: yes
        state: start
